/**
 * One-line "what is this page for" copy, keyed by route path — shown on the
 * My Profile page's guide section, grouped the same way the sidebar is.
 * Not every route needs an entry; a missing one just falls back to a generic
 * message rather than blocking the page from rendering.
 */
export const PAGE_GUIDE: Record<string, string> = {
  '/overview': 'The landing dashboard — headline numbers across orders, sales and finance at a glance.',
  '/orders': 'Every order ever placed, searchable and filterable — the operational record of what has been sold.',
  '/admin-order': 'Place a new order on a customer\'s behalf: pick their depot, product and quantity, then confirm payment.',
  '/people': 'Everyone we hold a number for — customers and leads on one list, with wallet balance and order history for those who have an account.',
  '/customers': 'The customer directory — contact details, wallet balance, and order history per customer.',
  '/my-report': 'File your own daily activity report for your role (sales, security, ticketing, etc.).',
  '/expense-requests': 'Raise and track your own expense claims through the approval chain.',
  '/ticket': 'Loading tickets for paid orders — assign trucks, drivers and quantities, then print the ticket.',
  '/security/entry': 'Gate-in scan: confirm a ticketed truck has arrived at the depot before it loads.',
  '/security/exit': 'Gate-out scan: confirm a loaded truck has left the depot, closing out that ticket.',
  '/security-report': 'A read-only log of every truck that has passed through the gate, for a given period.',
  '/depots': 'The depot directory — locations, product capacity, and which products are priced there.',
  '/products': 'The product catalogue — fuel types and units sold across the business.',
  '/confirmed-payments': 'The finance report: every confirmed payment, order by order, with where the money came from and the customer\'s wallet balance before/after.',
  '/order-management': 'Find an order and correct it — reassign the customer or PFI, change the date, quantity or price. Changes carry through to the wallet hold and the batch stock.',
  '/payable-orders': 'Every order awaiting payment. Confirm payment to match a bank statement (or record it manually) against that specific order — wallet balance applies first, and any shortfall shows right there.',
  '/deposits': 'The wallet ledger — every credit and debit ever recorded against a customer\'s balance.',
  '/commissions': 'Commission owed to customers on their purchases, and its payment status.',
  '/commission-rates': 'The commission percentage configured per product/customer tier.',
  '/bank-accounts': 'The company\'s own bank accounts, and which depots/stations collect into which account.',
  '/bank-statements': 'Upload a bank statement so its credit lines can be matched to customer deposits automatically.',
  '/fleet-trucks': 'The company\'s own truck fleet — registration, capacity, and current status.',
  '/fleet-ledger': 'Running expense record for the fleet — fuel, maintenance, repairs per truck.',
  '/drivers': 'The driver directory used when assigning a truck to a loading ticket.',
  '/lpg': 'LPG division home — links into the LPG dashboard, plants, stock and sales registers.',
  '/lpg/dashboard': 'Headline numbers for the LPG (cylinder gas) side of the business.',
  '/lpg/plants': 'LPG filling plants — capacity and stock on hand.',
  '/lpg/stock': 'Cylinder stock movement register — filled, sold, returned.',
  '/lpg/sales': 'LPG sales register — cylinder sales recorded per station.',
  '/lpg-stations': 'LPG retail stations directory, their assigned bank accounts and staff.',
  '/lpg-orders': 'Orders placed through the LPG delivery channel.',
  '/lpg-order-request': 'LPG delivery order requests awaiting review before they become orders.',
  '/dangote-orders': 'Orders placed through the Dangote delivery/reseller channel.',
  '/dangote-order-request': 'Dangote order requests awaiting review and pricing before they become orders.',
  '/dangote-products': 'The product/price list specific to the Dangote channel.',
  '/licence-verification': 'Verify a customer\'s trucking/dealership licence before approving their order.',
  '/delivery-operations': 'Day-to-day management of truck-sales delivery orders.',
  '/delivery-customer': 'The delivery-channel customer directory, separate from the main customer list.',
  '/sales-ledger': 'Running sales record for the truck-sales delivery channel.',
  '/filing-stations': 'Filling-station directory for the truck-sales channel.',
  '/admin-reports': 'Reports Hub — every staff daily report submitted, in one place, exportable to Excel.',
  '/messaging': 'Send a broadcast message/notification to customers.',
  '/product-pricing': 'Set the per-depot price for each product.',
  '/pfi': 'PFI (Proforma Invoice / cargo batch) tracking — quantities, cost, sales and profit per batch.',
  '/expenses': 'Raise, review and approve company expenses through the approval chain.',
  '/vendors': 'The vendor directory used when recording an expense.',
  '/admin': 'Manage staff accounts — roles, location/PFI assignment, and page-access overrides.',
  '/feedback-dashboard': 'Customer feedback and reviews left through the customer portal.',
  '/profile': 'This page — your own account info, assignments, and what you can do on the dashboard.',
}
