/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as ActivityIndexRouteImport } from './routes/activity/index'
import { Route as AdminOrderIndexRouteImport } from './routes/admin-order/index'
import { Route as AdminOrderDangoteRequestFormRouteImport } from './routes/admin-order/dangote-request-form'
import { Route as AdminOrderDepotRouteImport } from './routes/admin-order/depot'
import { Route as AdminOrderLpgRequestFormRouteImport } from './routes/admin-order/lpg-request-form'
import { Route as AdminReportsIndexRouteImport } from './routes/admin-reports/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDetailsRouteImport } from './routes/admin/details'
import { Route as AdminFormRouteImport } from './routes/admin/form'
import { Route as AdminUpdateRouteImport } from './routes/admin/update'
import { Route as BankAccountsIndexRouteImport } from './routes/bank-accounts/index'
import { Route as BankAccountsDetailsRouteImport } from './routes/bank-accounts/details'
import { Route as BankAccountsFormRouteImport } from './routes/bank-accounts/form'
import { Route as BankStatementsIndexRouteImport } from './routes/bank-statements/index'
import { Route as CommissionRatesIndexRouteImport } from './routes/commission-rates/index'
import { Route as CommissionsIndexRouteImport } from './routes/commissions/index'
import { Route as CompanyDashboardIndexRouteImport } from './routes/company-dashboard/index'
import { Route as ConfirmedPaymentsIndexRouteImport } from './routes/confirmed-payments/index'
import { Route as ContactsIndexRouteImport } from './routes/contacts/index'
import { Route as CustomerDeskIndexRouteImport } from './routes/customer-desk/index'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as CustomersDetailsRouteImport } from './routes/customers/details'
import { Route as CustomersFormRouteImport } from './routes/customers/form'
import { Route as DangoteOrderRequestIndexRouteImport } from './routes/dangote-order-request/index'
import { Route as DangoteOrderRequestReviewRouteImport } from './routes/dangote-order-request/review'
import { Route as DangoteOrdersIndexRouteImport } from './routes/dangote-orders/index'
import { Route as DangoteOrdersDetailsRouteImport } from './routes/dangote-orders/details'
import { Route as DangotePayableOrdersIndexRouteImport } from './routes/dangote-payable-orders/index'
import { Route as DangoteProductsIndexRouteImport } from './routes/dangote-products/index'
import { Route as DangoteProductsDetailsRouteImport } from './routes/dangote-products/details'
import { Route as DangoteProductsFormRouteImport } from './routes/dangote-products/form'
import { Route as DeliveryCustomerIndexRouteImport } from './routes/delivery-customer/index'
import { Route as DeliveryCustomerDetailsRouteImport } from './routes/delivery-customer/details'
import { Route as DeliveryCustomerFormRouteImport } from './routes/delivery-customer/form'
import { Route as DeliveryInventoryIndexRouteImport } from './routes/delivery-inventory/index'
import { Route as DeliveryOperationsIndexRouteImport } from './routes/delivery-operations/index'
import { Route as DeliveryOperationsAllocateTrucksRouteImport } from './routes/delivery-operations/allocate-trucks'
import { Route as DeliveryOperationsAllocationDetailsRouteImport } from './routes/delivery-operations/allocation-details'
import { Route as DeliveryOperationsDetailsRouteImport } from './routes/delivery-operations/details'
import { Route as DepositsIndexRouteImport } from './routes/deposits/index'
import { Route as DepositsDetailsRouteImport } from './routes/deposits/details'
import { Route as DepositsManualDepositRouteImport } from './routes/deposits/manual-deposit'
import { Route as DepotsIndexRouteImport } from './routes/depots/index'
import { Route as DepotsDetailsRouteImport } from './routes/depots/details'
import { Route as DepotsFormRouteImport } from './routes/depots/form'
import { Route as DriversIndexRouteImport } from './routes/drivers/index'
import { Route as DriversDetailsRouteImport } from './routes/drivers/details'
import { Route as DriversFormRouteImport } from './routes/drivers/form'
import { Route as ExpenseRequestsIndexRouteImport } from './routes/expense-requests/index'
import { Route as ExpensesIndexRouteImport } from './routes/expenses/index'
import { Route as FeedbackDashboardIndexRouteImport } from './routes/feedback-dashboard/index'
import { Route as FilingStationsIndexRouteImport } from './routes/filing-stations/index'
import { Route as FilingStationsDetailsRouteImport } from './routes/filing-stations/details'
import { Route as FilingStationsFormRouteImport } from './routes/filing-stations/form'
import { Route as FleetLedgerIndexRouteImport } from './routes/fleet-ledger/index'
import { Route as FleetTrucksIndexRouteImport } from './routes/fleet-trucks/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as LicenceVerificationIndexRouteImport } from './routes/licence-verification/index'
import { Route as LicenceVerificationReviewRouteImport } from './routes/licence-verification/review'
import { Route as LpgOrderRequestIndexRouteImport } from './routes/lpg-order-request/index'
import { Route as LpgOrderRequestReviewRouteImport } from './routes/lpg-order-request/review'
import { Route as LpgOrdersIndexRouteImport } from './routes/lpg-orders/index'
import { Route as LpgOrdersDetailsRouteImport } from './routes/lpg-orders/details'
import { Route as LpgPayableOrdersIndexRouteImport } from './routes/lpg-payable-orders/index'
import { Route as LpgStationsIndexRouteImport } from './routes/lpg-stations/index'
import { Route as LpgStationsDetailsRouteImport } from './routes/lpg-stations/details'
import { Route as LpgStationsFormRouteImport } from './routes/lpg-stations/form'
import { Route as LpgIndexRouteImport } from './routes/lpg/index'
import { Route as MessagingIndexRouteImport } from './routes/messaging/index'
import { Route as MyReportIndexRouteImport } from './routes/my-report/index'
import { Route as OrderAuditIndexRouteImport } from './routes/order-audit/index'
import { Route as OrderManagementIndexRouteImport } from './routes/order-management/index'
import { Route as OrdersPfiIndexRouteImport } from './routes/orders-pfi/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as OrdersDetailsRouteImport } from './routes/orders/details'
import { Route as OverpaymentRefundsIndexRouteImport } from './routes/overpayment-refunds/index'
import { Route as OverpaymentRequestsIndexRouteImport } from './routes/overpayment-requests/index'
import { Route as OverviewIndexRouteImport } from './routes/overview/index'
import { Route as PayableOrdersIndexRouteImport } from './routes/payable-orders/index'
import { Route as PaymentVerifyIndexRouteImport } from './routes/payment-verify/index'
import { Route as PeopleIndexRouteImport } from './routes/people/index'
import { Route as PfiIndexRouteImport } from './routes/pfi/index'
import { Route as PfiDetailsRouteImport } from './routes/pfi/details'
import { Route as PfiFormRouteImport } from './routes/pfi/form'
import { Route as ProductManagerViewIndexRouteImport } from './routes/product-manager-view/index'
import { Route as ProductPricingIndexRouteImport } from './routes/product-pricing/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsDetailsRouteImport } from './routes/products/details'
import { Route as ProductsFormRouteImport } from './routes/products/form'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as SalesLedgerIndexRouteImport } from './routes/sales-ledger/index'
import { Route as SalesLedgerAssignCustomerRouteImport } from './routes/sales-ledger/assign-customer'
import { Route as SalesLedgerDetailsRouteImport } from './routes/sales-ledger/details'
import { Route as SalesManagerViewIndexRouteImport } from './routes/sales-manager-view/index'
import { Route as SecurityReportIndexRouteImport } from './routes/security-report/index'
import { Route as SecurityEntryRouteImport } from './routes/security/entry'
import { Route as SecurityExitRouteImport } from './routes/security/exit'
import { Route as TicketIndexRouteImport } from './routes/ticket/index'
import { Route as TicketDetailsRouteImport } from './routes/ticket/details'
import { Route as TicketGenerateRouteImport } from './routes/ticket/generate'
import { Route as VendorsIndexRouteImport } from './routes/vendors/index'
import { Route as VendorsDetailsRouteImport } from './routes/vendors/details'
import { Route as VendorsFormRouteImport } from './routes/vendors/form'
import { Route as LpgDashboardIndexRouteImport } from './routes/lpg/dashboard/index'
import { Route as LpgPlantsIndexRouteImport } from './routes/lpg/plants/index'
import { Route as LpgSalesIndexRouteImport } from './routes/lpg/sales/index'
import { Route as LpgStockIndexRouteImport } from './routes/lpg/stock/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityIndexRoute = ActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrderIndexRoute = AdminOrderIndexRouteImport.update({
  id: '/admin-order/',
  path: '/admin-order/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrderDangoteRequestFormRoute =
  AdminOrderDangoteRequestFormRouteImport.update({
    id: '/admin-order/dangote-request-form',
    path: '/admin-order/dangote-request-form',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminOrderDepotRoute = AdminOrderDepotRouteImport.update({
  id: '/admin-order/depot',
  path: '/admin-order/depot',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrderLpgRequestFormRoute =
  AdminOrderLpgRequestFormRouteImport.update({
    id: '/admin-order/lpg-request-form',
    path: '/admin-order/lpg-request-form',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminReportsIndexRoute = AdminReportsIndexRouteImport.update({
  id: '/admin-reports/',
  path: '/admin-reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDetailsRoute = AdminDetailsRouteImport.update({
  id: '/admin/details',
  path: '/admin/details',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFormRoute = AdminFormRouteImport.update({
  id: '/admin/form',
  path: '/admin/form',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUpdateRoute = AdminUpdateRouteImport.update({
  id: '/admin/update',
  path: '/admin/update',
  getParentRoute: () => rootRouteImport,
} as any)
const BankAccountsIndexRoute = BankAccountsIndexRouteImport.update({
  id: '/bank-accounts/',
  path: '/bank-accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const BankAccountsDetailsRoute = BankAccountsDetailsRouteImport.update({
  id: '/bank-accounts/details',
  path: '/bank-accounts/details',
  getParentRoute: () => rootRouteImport,
} as any)
const BankAccountsFormRoute = BankAccountsFormRouteImport.update({
  id: '/bank-accounts/form',
  path: '/bank-accounts/form',
  getParentRoute: () => rootRouteImport,
} as any)
const BankStatementsIndexRoute = BankStatementsIndexRouteImport.update({
  id: '/bank-statements/',
  path: '/bank-statements/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionRatesIndexRoute = CommissionRatesIndexRouteImport.update({
  id: '/commission-rates/',
  path: '/commission-rates/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionsIndexRoute = CommissionsIndexRouteImport.update({
  id: '/commissions/',
  path: '/commissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyDashboardIndexRoute = CompanyDashboardIndexRouteImport.update({
  id: '/company-dashboard/',
  path: '/company-dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmedPaymentsIndexRoute = ConfirmedPaymentsIndexRouteImport.update({
  id: '/confirmed-payments/',
  path: '/confirmed-payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDeskIndexRoute = CustomerDeskIndexRouteImport.update({
  id: '/customer-desk/',
  path: '/customer-desk/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersDetailsRoute = CustomersDetailsRouteImport.update({
  id: '/customers/details',
  path: '/customers/details',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersFormRoute = CustomersFormRouteImport.update({
  id: '/customers/form',
  path: '/customers/form',
  getParentRoute: () => rootRouteImport,
} as any)
const DangoteOrderRequestIndexRoute =
  DangoteOrderRequestIndexRouteImport.update({
    id: '/dangote-order-request/',
    path: '/dangote-order-request/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DangoteOrderRequestReviewRoute =
  DangoteOrderRequestReviewRouteImport.update({
    id: '/dangote-order-request/review',
    path: '/dangote-order-request/review',
    getParentRoute: () => rootRouteImport,
  } as any)
const DangoteOrdersIndexRoute = DangoteOrdersIndexRouteImport.update({
  id: '/dangote-orders/',
  path: '/dangote-orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const DangoteOrdersDetailsRoute = DangoteOrdersDetailsRouteImport.update({
  id: '/dangote-orders/details',
  path: '/dangote-orders/details',
  getParentRoute: () => rootRouteImport,
} as any)
const DangotePayableOrdersIndexRoute =
  DangotePayableOrdersIndexRouteImport.update({
    id: '/dangote-payable-orders/',
    path: '/dangote-payable-orders/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DangoteProductsIndexRoute = DangoteProductsIndexRouteImport.update({
  id: '/dangote-products/',
  path: '/dangote-products/',
  getParentRoute: () => rootRouteImport,
} as any)
const DangoteProductsDetailsRoute = DangoteProductsDetailsRouteImport.update({
  id: '/dangote-products/details',
  path: '/dangote-products/details',
  getParentRoute: () => rootRouteImport,
} as any)
const DangoteProductsFormRoute = DangoteProductsFormRouteImport.update({
  id: '/dangote-products/form',
  path: '/dangote-products/form',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryCustomerIndexRoute = DeliveryCustomerIndexRouteImport.update({
  id: '/delivery-customer/',
  path: '/delivery-customer/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryCustomerDetailsRoute = DeliveryCustomerDetailsRouteImport.update({
  id: '/delivery-customer/details',
  path: '/delivery-customer/details',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryCustomerFormRoute = DeliveryCustomerFormRouteImport.update({
  id: '/delivery-customer/form',
  path: '/delivery-customer/form',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryInventoryIndexRoute = DeliveryInventoryIndexRouteImport.update({
  id: '/delivery-inventory/',
  path: '/delivery-inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryOperationsIndexRoute = DeliveryOperationsIndexRouteImport.update({
  id: '/delivery-operations/',
  path: '/delivery-operations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryOperationsAllocateTrucksRoute =
  DeliveryOperationsAllocateTrucksRouteImport.update({
    id: '/delivery-operations/allocate-trucks',
    path: '/delivery-operations/allocate-trucks',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeliveryOperationsAllocationDetailsRoute =
  DeliveryOperationsAllocationDetailsRouteImport.update({
    id: '/delivery-operations/allocation-details',
    path: '/delivery-operations/allocation-details',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeliveryOperationsDetailsRoute =
  DeliveryOperationsDetailsRouteImport.update({
    id: '/delivery-operations/details',
    path: '/delivery-operations/details',
    getParentRoute: () => rootRouteImport,
  } as any)
const DepositsIndexRoute = DepositsIndexRouteImport.update({
  id: '/deposits/',
  path: '/deposits/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositsDetailsRoute = DepositsDetailsRouteImport.update({
  id: '/deposits/details',
  path: '/deposits/details',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositsManualDepositRoute = DepositsManualDepositRouteImport.update({
  id: '/deposits/manual-deposit',
  path: '/deposits/manual-deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const DepotsIndexRoute = DepotsIndexRouteImport.update({
  id: '/depots/',
  path: '/depots/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepotsDetailsRoute = DepotsDetailsRouteImport.update({
  id: '/depots/details',
  path: '/depots/details',
  getParentRoute: () => rootRouteImport,
} as any)
const DepotsFormRoute = DepotsFormRouteImport.update({
  id: '/depots/form',
  path: '/depots/form',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversIndexRoute = DriversIndexRouteImport.update({
  id: '/drivers/',
  path: '/drivers/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversDetailsRoute = DriversDetailsRouteImport.update({
  id: '/drivers/details',
  path: '/drivers/details',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversFormRoute = DriversFormRouteImport.update({
  id: '/drivers/form',
  path: '/drivers/form',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpenseRequestsIndexRoute = ExpenseRequestsIndexRouteImport.update({
  id: '/expense-requests/',
  path: '/expense-requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesIndexRoute = ExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackDashboardIndexRoute = FeedbackDashboardIndexRouteImport.update({
  id: '/feedback-dashboard/',
  path: '/feedback-dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilingStationsIndexRoute = FilingStationsIndexRouteImport.update({
  id: '/filing-stations/',
  path: '/filing-stations/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilingStationsDetailsRoute = FilingStationsDetailsRouteImport.update({
  id: '/filing-stations/details',
  path: '/filing-stations/details',
  getParentRoute: () => rootRouteImport,
} as any)
const FilingStationsFormRoute = FilingStationsFormRouteImport.update({
  id: '/filing-stations/form',
  path: '/filing-stations/form',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetLedgerIndexRoute = FleetLedgerIndexRouteImport.update({
  id: '/fleet-ledger/',
  path: '/fleet-ledger/',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetTrucksIndexRoute = FleetTrucksIndexRouteImport.update({
  id: '/fleet-trucks/',
  path: '/fleet-trucks/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenceVerificationIndexRoute =
  LicenceVerificationIndexRouteImport.update({
    id: '/licence-verification/',
    path: '/licence-verification/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LicenceVerificationReviewRoute =
  LicenceVerificationReviewRouteImport.update({
    id: '/licence-verification/review',
    path: '/licence-verification/review',
    getParentRoute: () => rootRouteImport,
  } as any)
const LpgOrderRequestIndexRoute = LpgOrderRequestIndexRouteImport.update({
  id: '/lpg-order-request/',
  path: '/lpg-order-request/',
  getParentRoute: () => rootRouteImport,
} as any)
const LpgOrderRequestReviewRoute = LpgOrderRequestReviewRouteImport.update({
  id: '/lpg-order-request/review',
  path: '/lpg-order-request/review',
  getParentRoute: () => rootRouteImport,
} as any)
const LpgOrdersIndexRoute = LpgOrdersIndexRouteImport.update({
  id: '/lpg-orders/',
  path: '/lpg-orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const LpgOrdersDetailsRoute = LpgOrdersDetailsRouteImport.update({
  id: '/lpg-orders/details',
  path: '/lpg-orders/details',
  getParentRoute: () => rootRouteImport,
} as any)
const LpgPayableOrdersIndexRoute = LpgPayableOrdersIndexRouteImport.update({
  id: '/lpg-payable-orders/',
  path: '/lpg-payable-orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const LpgStationsIndexRoute = LpgStationsIndexRouteImport.update({
  id: '/lpg-stations/',
  path: '/lpg-stations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LpgStationsDetailsRoute = LpgStationsDetailsRouteImport.update({
  id: '/lpg-stations/details',
  path: '/lpg-stations/details',
  getParentRoute: () => rootRouteImport,
} as any)
const LpgStationsFormRoute = LpgStationsFormRouteImport.update({
  id: '/lpg-stations/form',
  path: '/lpg-stations/form',
  getParentRoute: () => rootRouteImport,
} as any)
const LpgIndexRoute = LpgIndexRouteImport.update({
  id: '/lpg/',
  path: '/lpg/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagingIndexRoute = MessagingIndexRouteImport.update({
  id: '/messaging/',
  path: '/messaging/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyReportIndexRoute = MyReportIndexRouteImport.update({
  id: '/my-report/',
  path: '/my-report/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderAuditIndexRoute = OrderAuditIndexRouteImport.update({
  id: '/order-audit/',
  path: '/order-audit/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderManagementIndexRoute = OrderManagementIndexRouteImport.update({
  id: '/order-management/',
  path: '/order-management/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersPfiIndexRoute = OrdersPfiIndexRouteImport.update({
  id: '/orders-pfi/',
  path: '/orders-pfi/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersDetailsRoute = OrdersDetailsRouteImport.update({
  id: '/orders/details',
  path: '/orders/details',
  getParentRoute: () => rootRouteImport,
} as any)
const OverpaymentRefundsIndexRoute = OverpaymentRefundsIndexRouteImport.update({
  id: '/overpayment-refunds/',
  path: '/overpayment-refunds/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverpaymentRequestsIndexRoute =
  OverpaymentRequestsIndexRouteImport.update({
    id: '/overpayment-requests/',
    path: '/overpayment-requests/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OverviewIndexRoute = OverviewIndexRouteImport.update({
  id: '/overview/',
  path: '/overview/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayableOrdersIndexRoute = PayableOrdersIndexRouteImport.update({
  id: '/payable-orders/',
  path: '/payable-orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentVerifyIndexRoute = PaymentVerifyIndexRouteImport.update({
  id: '/payment-verify/',
  path: '/payment-verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => rootRouteImport,
} as any)
const PfiIndexRoute = PfiIndexRouteImport.update({
  id: '/pfi/',
  path: '/pfi/',
  getParentRoute: () => rootRouteImport,
} as any)
const PfiDetailsRoute = PfiDetailsRouteImport.update({
  id: '/pfi/details',
  path: '/pfi/details',
  getParentRoute: () => rootRouteImport,
} as any)
const PfiFormRoute = PfiFormRouteImport.update({
  id: '/pfi/form',
  path: '/pfi/form',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductManagerViewIndexRoute = ProductManagerViewIndexRouteImport.update({
  id: '/product-manager-view/',
  path: '/product-manager-view/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductPricingIndexRoute = ProductPricingIndexRouteImport.update({
  id: '/product-pricing/',
  path: '/product-pricing/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsDetailsRoute = ProductsDetailsRouteImport.update({
  id: '/products/details',
  path: '/products/details',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsFormRoute = ProductsFormRouteImport.update({
  id: '/products/form',
  path: '/products/form',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesLedgerIndexRoute = SalesLedgerIndexRouteImport.update({
  id: '/sales-ledger/',
  path: '/sales-ledger/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesLedgerAssignCustomerRoute =
  SalesLedgerAssignCustomerRouteImport.update({
    id: '/sales-ledger/assign-customer',
    path: '/sales-ledger/assign-customer',
    getParentRoute: () => rootRouteImport,
  } as any)
const SalesLedgerDetailsRoute = SalesLedgerDetailsRouteImport.update({
  id: '/sales-ledger/details',
  path: '/sales-ledger/details',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesManagerViewIndexRoute = SalesManagerViewIndexRouteImport.update({
  id: '/sales-manager-view/',
  path: '/sales-manager-view/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityReportIndexRoute = SecurityReportIndexRouteImport.update({
  id: '/security-report/',
  path: '/security-report/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityEntryRoute = SecurityEntryRouteImport.update({
  id: '/security/entry',
  path: '/security/entry',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityExitRoute = SecurityExitRouteImport.update({
  id: '/security/exit',
  path: '/security/exit',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketIndexRoute = TicketIndexRouteImport.update({
  id: '/ticket/',
  path: '/ticket/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketDetailsRoute = TicketDetailsRouteImport.update({
  id: '/ticket/details',
  path: '/ticket/details',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketGenerateRoute = TicketGenerateRouteImport.update({
  id: '/ticket/generate',
  path: '/ticket/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIndexRoute = VendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsDetailsRoute = VendorsDetailsRouteImport.update({
  id: '/vendors/details',
  path: '/vendors/details',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsFormRoute = VendorsFormRouteImport.update({
  id: '/vendors/form',
  path: '/vendors/form',
  getParentRoute: () => rootRouteImport,
} as any)
const LpgDashboardIndexRoute = LpgDashboardIndexRouteImport.update({
  id: '/lpg/dashboard/',
  path: '/lpg/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const LpgPlantsIndexRoute = LpgPlantsIndexRouteImport.update({
  id: '/lpg/plants/',
  path: '/lpg/plants/',
  getParentRoute: () => rootRouteImport,
} as any)
const LpgSalesIndexRoute = LpgSalesIndexRouteImport.update({
  id: '/lpg/sales/',
  path: '/lpg/sales/',
  getParentRoute: () => rootRouteImport,
} as any)
const LpgStockIndexRoute = LpgStockIndexRouteImport.update({
  id: '/lpg/stock/',
  path: '/lpg/stock/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/admin-order/dangote-request-form': typeof AdminOrderDangoteRequestFormRoute
  '/admin-order/depot': typeof AdminOrderDepotRoute
  '/admin-order/lpg-request-form': typeof AdminOrderLpgRequestFormRoute
  '/admin/details': typeof AdminDetailsRoute
  '/admin/form': typeof AdminFormRoute
  '/admin/update': typeof AdminUpdateRoute
  '/bank-accounts/details': typeof BankAccountsDetailsRoute
  '/bank-accounts/form': typeof BankAccountsFormRoute
  '/customers/details': typeof CustomersDetailsRoute
  '/customers/form': typeof CustomersFormRoute
  '/dangote-order-request/review': typeof DangoteOrderRequestReviewRoute
  '/dangote-orders/details': typeof DangoteOrdersDetailsRoute
  '/dangote-products/details': typeof DangoteProductsDetailsRoute
  '/dangote-products/form': typeof DangoteProductsFormRoute
  '/delivery-customer/details': typeof DeliveryCustomerDetailsRoute
  '/delivery-customer/form': typeof DeliveryCustomerFormRoute
  '/delivery-operations/allocate-trucks': typeof DeliveryOperationsAllocateTrucksRoute
  '/delivery-operations/allocation-details': typeof DeliveryOperationsAllocationDetailsRoute
  '/delivery-operations/details': typeof DeliveryOperationsDetailsRoute
  '/deposits/details': typeof DepositsDetailsRoute
  '/deposits/manual-deposit': typeof DepositsManualDepositRoute
  '/depots/details': typeof DepotsDetailsRoute
  '/depots/form': typeof DepotsFormRoute
  '/drivers/details': typeof DriversDetailsRoute
  '/drivers/form': typeof DriversFormRoute
  '/filing-stations/details': typeof FilingStationsDetailsRoute
  '/filing-stations/form': typeof FilingStationsFormRoute
  '/licence-verification/review': typeof LicenceVerificationReviewRoute
  '/lpg-order-request/review': typeof LpgOrderRequestReviewRoute
  '/lpg-orders/details': typeof LpgOrdersDetailsRoute
  '/lpg-stations/details': typeof LpgStationsDetailsRoute
  '/lpg-stations/form': typeof LpgStationsFormRoute
  '/orders/details': typeof OrdersDetailsRoute
  '/pfi/details': typeof PfiDetailsRoute
  '/pfi/form': typeof PfiFormRoute
  '/products/details': typeof ProductsDetailsRoute
  '/products/form': typeof ProductsFormRoute
  '/sales-ledger/assign-customer': typeof SalesLedgerAssignCustomerRoute
  '/sales-ledger/details': typeof SalesLedgerDetailsRoute
  '/security/entry': typeof SecurityEntryRoute
  '/security/exit': typeof SecurityExitRoute
  '/ticket/details': typeof TicketDetailsRoute
  '/ticket/generate': typeof TicketGenerateRoute
  '/vendors/details': typeof VendorsDetailsRoute
  '/vendors/form': typeof VendorsFormRoute
  '/activity/': typeof ActivityIndexRoute
  '/admin-order/': typeof AdminOrderIndexRoute
  '/admin-reports/': typeof AdminReportsIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/bank-accounts/': typeof BankAccountsIndexRoute
  '/bank-statements/': typeof BankStatementsIndexRoute
  '/commission-rates/': typeof CommissionRatesIndexRoute
  '/commissions/': typeof CommissionsIndexRoute
  '/company-dashboard/': typeof CompanyDashboardIndexRoute
  '/confirmed-payments/': typeof ConfirmedPaymentsIndexRoute
  '/contacts/': typeof ContactsIndexRoute
  '/customer-desk/': typeof CustomerDeskIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/dangote-order-request/': typeof DangoteOrderRequestIndexRoute
  '/dangote-orders/': typeof DangoteOrdersIndexRoute
  '/dangote-payable-orders/': typeof DangotePayableOrdersIndexRoute
  '/dangote-products/': typeof DangoteProductsIndexRoute
  '/delivery-customer/': typeof DeliveryCustomerIndexRoute
  '/delivery-inventory/': typeof DeliveryInventoryIndexRoute
  '/delivery-operations/': typeof DeliveryOperationsIndexRoute
  '/deposits/': typeof DepositsIndexRoute
  '/depots/': typeof DepotsIndexRoute
  '/drivers/': typeof DriversIndexRoute
  '/expense-requests/': typeof ExpenseRequestsIndexRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/feedback-dashboard/': typeof FeedbackDashboardIndexRoute
  '/filing-stations/': typeof FilingStationsIndexRoute
  '/fleet-ledger/': typeof FleetLedgerIndexRoute
  '/fleet-trucks/': typeof FleetTrucksIndexRoute
  '/home/': typeof HomeIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/licence-verification/': typeof LicenceVerificationIndexRoute
  '/lpg-order-request/': typeof LpgOrderRequestIndexRoute
  '/lpg-orders/': typeof LpgOrdersIndexRoute
  '/lpg-payable-orders/': typeof LpgPayableOrdersIndexRoute
  '/lpg-stations/': typeof LpgStationsIndexRoute
  '/lpg/': typeof LpgIndexRoute
  '/messaging/': typeof MessagingIndexRoute
  '/my-report/': typeof MyReportIndexRoute
  '/order-audit/': typeof OrderAuditIndexRoute
  '/order-management/': typeof OrderManagementIndexRoute
  '/orders-pfi/': typeof OrdersPfiIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/overpayment-refunds/': typeof OverpaymentRefundsIndexRoute
  '/overpayment-requests/': typeof OverpaymentRequestsIndexRoute
  '/overview/': typeof OverviewIndexRoute
  '/payable-orders/': typeof PayableOrdersIndexRoute
  '/payment-verify/': typeof PaymentVerifyIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/pfi/': typeof PfiIndexRoute
  '/product-manager-view/': typeof ProductManagerViewIndexRoute
  '/product-pricing/': typeof ProductPricingIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/sales-ledger/': typeof SalesLedgerIndexRoute
  '/sales-manager-view/': typeof SalesManagerViewIndexRoute
  '/security-report/': typeof SecurityReportIndexRoute
  '/ticket/': typeof TicketIndexRoute
  '/vendors/': typeof VendorsIndexRoute
  '/lpg/dashboard/': typeof LpgDashboardIndexRoute
  '/lpg/plants/': typeof LpgPlantsIndexRoute
  '/lpg/sales/': typeof LpgSalesIndexRoute
  '/lpg/stock/': typeof LpgStockIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/admin-order/dangote-request-form': typeof AdminOrderDangoteRequestFormRoute
  '/admin-order/depot': typeof AdminOrderDepotRoute
  '/admin-order/lpg-request-form': typeof AdminOrderLpgRequestFormRoute
  '/admin/details': typeof AdminDetailsRoute
  '/admin/form': typeof AdminFormRoute
  '/admin/update': typeof AdminUpdateRoute
  '/bank-accounts/details': typeof BankAccountsDetailsRoute
  '/bank-accounts/form': typeof BankAccountsFormRoute
  '/customers/details': typeof CustomersDetailsRoute
  '/customers/form': typeof CustomersFormRoute
  '/dangote-order-request/review': typeof DangoteOrderRequestReviewRoute
  '/dangote-orders/details': typeof DangoteOrdersDetailsRoute
  '/dangote-products/details': typeof DangoteProductsDetailsRoute
  '/dangote-products/form': typeof DangoteProductsFormRoute
  '/delivery-customer/details': typeof DeliveryCustomerDetailsRoute
  '/delivery-customer/form': typeof DeliveryCustomerFormRoute
  '/delivery-operations/allocate-trucks': typeof DeliveryOperationsAllocateTrucksRoute
  '/delivery-operations/allocation-details': typeof DeliveryOperationsAllocationDetailsRoute
  '/delivery-operations/details': typeof DeliveryOperationsDetailsRoute
  '/deposits/details': typeof DepositsDetailsRoute
  '/deposits/manual-deposit': typeof DepositsManualDepositRoute
  '/depots/details': typeof DepotsDetailsRoute
  '/depots/form': typeof DepotsFormRoute
  '/drivers/details': typeof DriversDetailsRoute
  '/drivers/form': typeof DriversFormRoute
  '/filing-stations/details': typeof FilingStationsDetailsRoute
  '/filing-stations/form': typeof FilingStationsFormRoute
  '/licence-verification/review': typeof LicenceVerificationReviewRoute
  '/lpg-order-request/review': typeof LpgOrderRequestReviewRoute
  '/lpg-orders/details': typeof LpgOrdersDetailsRoute
  '/lpg-stations/details': typeof LpgStationsDetailsRoute
  '/lpg-stations/form': typeof LpgStationsFormRoute
  '/orders/details': typeof OrdersDetailsRoute
  '/pfi/details': typeof PfiDetailsRoute
  '/pfi/form': typeof PfiFormRoute
  '/products/details': typeof ProductsDetailsRoute
  '/products/form': typeof ProductsFormRoute
  '/sales-ledger/assign-customer': typeof SalesLedgerAssignCustomerRoute
  '/sales-ledger/details': typeof SalesLedgerDetailsRoute
  '/security/entry': typeof SecurityEntryRoute
  '/security/exit': typeof SecurityExitRoute
  '/ticket/details': typeof TicketDetailsRoute
  '/ticket/generate': typeof TicketGenerateRoute
  '/vendors/details': typeof VendorsDetailsRoute
  '/vendors/form': typeof VendorsFormRoute
  '/activity': typeof ActivityIndexRoute
  '/admin-order': typeof AdminOrderIndexRoute
  '/admin-reports': typeof AdminReportsIndexRoute
  '/admin': typeof AdminIndexRoute
  '/bank-accounts': typeof BankAccountsIndexRoute
  '/bank-statements': typeof BankStatementsIndexRoute
  '/commission-rates': typeof CommissionRatesIndexRoute
  '/commissions': typeof CommissionsIndexRoute
  '/company-dashboard': typeof CompanyDashboardIndexRoute
  '/confirmed-payments': typeof ConfirmedPaymentsIndexRoute
  '/contacts': typeof ContactsIndexRoute
  '/customer-desk': typeof CustomerDeskIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/dangote-order-request': typeof DangoteOrderRequestIndexRoute
  '/dangote-orders': typeof DangoteOrdersIndexRoute
  '/dangote-payable-orders': typeof DangotePayableOrdersIndexRoute
  '/dangote-products': typeof DangoteProductsIndexRoute
  '/delivery-customer': typeof DeliveryCustomerIndexRoute
  '/delivery-inventory': typeof DeliveryInventoryIndexRoute
  '/delivery-operations': typeof DeliveryOperationsIndexRoute
  '/deposits': typeof DepositsIndexRoute
  '/depots': typeof DepotsIndexRoute
  '/drivers': typeof DriversIndexRoute
  '/expense-requests': typeof ExpenseRequestsIndexRoute
  '/expenses': typeof ExpensesIndexRoute
  '/feedback-dashboard': typeof FeedbackDashboardIndexRoute
  '/filing-stations': typeof FilingStationsIndexRoute
  '/fleet-ledger': typeof FleetLedgerIndexRoute
  '/fleet-trucks': typeof FleetTrucksIndexRoute
  '/home': typeof HomeIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/licence-verification': typeof LicenceVerificationIndexRoute
  '/lpg-order-request': typeof LpgOrderRequestIndexRoute
  '/lpg-orders': typeof LpgOrdersIndexRoute
  '/lpg-payable-orders': typeof LpgPayableOrdersIndexRoute
  '/lpg-stations': typeof LpgStationsIndexRoute
  '/lpg': typeof LpgIndexRoute
  '/messaging': typeof MessagingIndexRoute
  '/my-report': typeof MyReportIndexRoute
  '/order-audit': typeof OrderAuditIndexRoute
  '/order-management': typeof OrderManagementIndexRoute
  '/orders-pfi': typeof OrdersPfiIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/overpayment-refunds': typeof OverpaymentRefundsIndexRoute
  '/overpayment-requests': typeof OverpaymentRequestsIndexRoute
  '/overview': typeof OverviewIndexRoute
  '/payable-orders': typeof PayableOrdersIndexRoute
  '/payment-verify': typeof PaymentVerifyIndexRoute
  '/people': typeof PeopleIndexRoute
  '/pfi': typeof PfiIndexRoute
  '/product-manager-view': typeof ProductManagerViewIndexRoute
  '/product-pricing': typeof ProductPricingIndexRoute
  '/products': typeof ProductsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/sales-ledger': typeof SalesLedgerIndexRoute
  '/sales-manager-view': typeof SalesManagerViewIndexRoute
  '/security-report': typeof SecurityReportIndexRoute
  '/ticket': typeof TicketIndexRoute
  '/vendors': typeof VendorsIndexRoute
  '/lpg/dashboard': typeof LpgDashboardIndexRoute
  '/lpg/plants': typeof LpgPlantsIndexRoute
  '/lpg/sales': typeof LpgSalesIndexRoute
  '/lpg/stock': typeof LpgStockIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/admin-order/dangote-request-form': typeof AdminOrderDangoteRequestFormRoute
  '/admin-order/depot': typeof AdminOrderDepotRoute
  '/admin-order/lpg-request-form': typeof AdminOrderLpgRequestFormRoute
  '/admin/details': typeof AdminDetailsRoute
  '/admin/form': typeof AdminFormRoute
  '/admin/update': typeof AdminUpdateRoute
  '/bank-accounts/details': typeof BankAccountsDetailsRoute
  '/bank-accounts/form': typeof BankAccountsFormRoute
  '/customers/details': typeof CustomersDetailsRoute
  '/customers/form': typeof CustomersFormRoute
  '/dangote-order-request/review': typeof DangoteOrderRequestReviewRoute
  '/dangote-orders/details': typeof DangoteOrdersDetailsRoute
  '/dangote-products/details': typeof DangoteProductsDetailsRoute
  '/dangote-products/form': typeof DangoteProductsFormRoute
  '/delivery-customer/details': typeof DeliveryCustomerDetailsRoute
  '/delivery-customer/form': typeof DeliveryCustomerFormRoute
  '/delivery-operations/allocate-trucks': typeof DeliveryOperationsAllocateTrucksRoute
  '/delivery-operations/allocation-details': typeof DeliveryOperationsAllocationDetailsRoute
  '/delivery-operations/details': typeof DeliveryOperationsDetailsRoute
  '/deposits/details': typeof DepositsDetailsRoute
  '/deposits/manual-deposit': typeof DepositsManualDepositRoute
  '/depots/details': typeof DepotsDetailsRoute
  '/depots/form': typeof DepotsFormRoute
  '/drivers/details': typeof DriversDetailsRoute
  '/drivers/form': typeof DriversFormRoute
  '/filing-stations/details': typeof FilingStationsDetailsRoute
  '/filing-stations/form': typeof FilingStationsFormRoute
  '/licence-verification/review': typeof LicenceVerificationReviewRoute
  '/lpg-order-request/review': typeof LpgOrderRequestReviewRoute
  '/lpg-orders/details': typeof LpgOrdersDetailsRoute
  '/lpg-stations/details': typeof LpgStationsDetailsRoute
  '/lpg-stations/form': typeof LpgStationsFormRoute
  '/orders/details': typeof OrdersDetailsRoute
  '/pfi/details': typeof PfiDetailsRoute
  '/pfi/form': typeof PfiFormRoute
  '/products/details': typeof ProductsDetailsRoute
  '/products/form': typeof ProductsFormRoute
  '/sales-ledger/assign-customer': typeof SalesLedgerAssignCustomerRoute
  '/sales-ledger/details': typeof SalesLedgerDetailsRoute
  '/security/entry': typeof SecurityEntryRoute
  '/security/exit': typeof SecurityExitRoute
  '/ticket/details': typeof TicketDetailsRoute
  '/ticket/generate': typeof TicketGenerateRoute
  '/vendors/details': typeof VendorsDetailsRoute
  '/vendors/form': typeof VendorsFormRoute
  '/activity/': typeof ActivityIndexRoute
  '/admin-order/': typeof AdminOrderIndexRoute
  '/admin-reports/': typeof AdminReportsIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/bank-accounts/': typeof BankAccountsIndexRoute
  '/bank-statements/': typeof BankStatementsIndexRoute
  '/commission-rates/': typeof CommissionRatesIndexRoute
  '/commissions/': typeof CommissionsIndexRoute
  '/company-dashboard/': typeof CompanyDashboardIndexRoute
  '/confirmed-payments/': typeof ConfirmedPaymentsIndexRoute
  '/contacts/': typeof ContactsIndexRoute
  '/customer-desk/': typeof CustomerDeskIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/dangote-order-request/': typeof DangoteOrderRequestIndexRoute
  '/dangote-orders/': typeof DangoteOrdersIndexRoute
  '/dangote-payable-orders/': typeof DangotePayableOrdersIndexRoute
  '/dangote-products/': typeof DangoteProductsIndexRoute
  '/delivery-customer/': typeof DeliveryCustomerIndexRoute
  '/delivery-inventory/': typeof DeliveryInventoryIndexRoute
  '/delivery-operations/': typeof DeliveryOperationsIndexRoute
  '/deposits/': typeof DepositsIndexRoute
  '/depots/': typeof DepotsIndexRoute
  '/drivers/': typeof DriversIndexRoute
  '/expense-requests/': typeof ExpenseRequestsIndexRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/feedback-dashboard/': typeof FeedbackDashboardIndexRoute
  '/filing-stations/': typeof FilingStationsIndexRoute
  '/fleet-ledger/': typeof FleetLedgerIndexRoute
  '/fleet-trucks/': typeof FleetTrucksIndexRoute
  '/home/': typeof HomeIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/licence-verification/': typeof LicenceVerificationIndexRoute
  '/lpg-order-request/': typeof LpgOrderRequestIndexRoute
  '/lpg-orders/': typeof LpgOrdersIndexRoute
  '/lpg-payable-orders/': typeof LpgPayableOrdersIndexRoute
  '/lpg-stations/': typeof LpgStationsIndexRoute
  '/lpg/': typeof LpgIndexRoute
  '/messaging/': typeof MessagingIndexRoute
  '/my-report/': typeof MyReportIndexRoute
  '/order-audit/': typeof OrderAuditIndexRoute
  '/order-management/': typeof OrderManagementIndexRoute
  '/orders-pfi/': typeof OrdersPfiIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/overpayment-refunds/': typeof OverpaymentRefundsIndexRoute
  '/overpayment-requests/': typeof OverpaymentRequestsIndexRoute
  '/overview/': typeof OverviewIndexRoute
  '/payable-orders/': typeof PayableOrdersIndexRoute
  '/payment-verify/': typeof PaymentVerifyIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/pfi/': typeof PfiIndexRoute
  '/product-manager-view/': typeof ProductManagerViewIndexRoute
  '/product-pricing/': typeof ProductPricingIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/sales-ledger/': typeof SalesLedgerIndexRoute
  '/sales-manager-view/': typeof SalesManagerViewIndexRoute
  '/security-report/': typeof SecurityReportIndexRoute
  '/ticket/': typeof TicketIndexRoute
  '/vendors/': typeof VendorsIndexRoute
  '/lpg/dashboard/': typeof LpgDashboardIndexRoute
  '/lpg/plants/': typeof LpgPlantsIndexRoute
  '/lpg/sales/': typeof LpgSalesIndexRoute
  '/lpg/stock/': typeof LpgStockIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/set-password'
    | '/admin-order/dangote-request-form'
    | '/admin-order/depot'
    | '/admin-order/lpg-request-form'
    | '/admin/details'
    | '/admin/form'
    | '/admin/update'
    | '/bank-accounts/details'
    | '/bank-accounts/form'
    | '/customers/details'
    | '/customers/form'
    | '/dangote-order-request/review'
    | '/dangote-orders/details'
    | '/dangote-products/details'
    | '/dangote-products/form'
    | '/delivery-customer/details'
    | '/delivery-customer/form'
    | '/delivery-operations/allocate-trucks'
    | '/delivery-operations/allocation-details'
    | '/delivery-operations/details'
    | '/deposits/details'
    | '/deposits/manual-deposit'
    | '/depots/details'
    | '/depots/form'
    | '/drivers/details'
    | '/drivers/form'
    | '/filing-stations/details'
    | '/filing-stations/form'
    | '/licence-verification/review'
    | '/lpg-order-request/review'
    | '/lpg-orders/details'
    | '/lpg-stations/details'
    | '/lpg-stations/form'
    | '/orders/details'
    | '/pfi/details'
    | '/pfi/form'
    | '/products/details'
    | '/products/form'
    | '/sales-ledger/assign-customer'
    | '/sales-ledger/details'
    | '/security/entry'
    | '/security/exit'
    | '/ticket/details'
    | '/ticket/generate'
    | '/vendors/details'
    | '/vendors/form'
    | '/activity/'
    | '/admin-order/'
    | '/admin-reports/'
    | '/admin/'
    | '/bank-accounts/'
    | '/bank-statements/'
    | '/commission-rates/'
    | '/commissions/'
    | '/company-dashboard/'
    | '/confirmed-payments/'
    | '/contacts/'
    | '/customer-desk/'
    | '/customers/'
    | '/dangote-order-request/'
    | '/dangote-orders/'
    | '/dangote-payable-orders/'
    | '/dangote-products/'
    | '/delivery-customer/'
    | '/delivery-inventory/'
    | '/delivery-operations/'
    | '/deposits/'
    | '/depots/'
    | '/drivers/'
    | '/expense-requests/'
    | '/expenses/'
    | '/feedback-dashboard/'
    | '/filing-stations/'
    | '/fleet-ledger/'
    | '/fleet-trucks/'
    | '/home/'
    | '/inventory/'
    | '/licence-verification/'
    | '/lpg-order-request/'
    | '/lpg-orders/'
    | '/lpg-payable-orders/'
    | '/lpg-stations/'
    | '/lpg/'
    | '/messaging/'
    | '/my-report/'
    | '/order-audit/'
    | '/order-management/'
    | '/orders-pfi/'
    | '/orders/'
    | '/overpayment-refunds/'
    | '/overpayment-requests/'
    | '/overview/'
    | '/payable-orders/'
    | '/payment-verify/'
    | '/people/'
    | '/pfi/'
    | '/product-manager-view/'
    | '/product-pricing/'
    | '/products/'
    | '/profile/'
    | '/sales-ledger/'
    | '/sales-manager-view/'
    | '/security-report/'
    | '/ticket/'
    | '/vendors/'
    | '/lpg/dashboard/'
    | '/lpg/plants/'
    | '/lpg/sales/'
    | '/lpg/stock/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/set-password'
    | '/admin-order/dangote-request-form'
    | '/admin-order/depot'
    | '/admin-order/lpg-request-form'
    | '/admin/details'
    | '/admin/form'
    | '/admin/update'
    | '/bank-accounts/details'
    | '/bank-accounts/form'
    | '/customers/details'
    | '/customers/form'
    | '/dangote-order-request/review'
    | '/dangote-orders/details'
    | '/dangote-products/details'
    | '/dangote-products/form'
    | '/delivery-customer/details'
    | '/delivery-customer/form'
    | '/delivery-operations/allocate-trucks'
    | '/delivery-operations/allocation-details'
    | '/delivery-operations/details'
    | '/deposits/details'
    | '/deposits/manual-deposit'
    | '/depots/details'
    | '/depots/form'
    | '/drivers/details'
    | '/drivers/form'
    | '/filing-stations/details'
    | '/filing-stations/form'
    | '/licence-verification/review'
    | '/lpg-order-request/review'
    | '/lpg-orders/details'
    | '/lpg-stations/details'
    | '/lpg-stations/form'
    | '/orders/details'
    | '/pfi/details'
    | '/pfi/form'
    | '/products/details'
    | '/products/form'
    | '/sales-ledger/assign-customer'
    | '/sales-ledger/details'
    | '/security/entry'
    | '/security/exit'
    | '/ticket/details'
    | '/ticket/generate'
    | '/vendors/details'
    | '/vendors/form'
    | '/activity'
    | '/admin-order'
    | '/admin-reports'
    | '/admin'
    | '/bank-accounts'
    | '/bank-statements'
    | '/commission-rates'
    | '/commissions'
    | '/company-dashboard'
    | '/confirmed-payments'
    | '/contacts'
    | '/customer-desk'
    | '/customers'
    | '/dangote-order-request'
    | '/dangote-orders'
    | '/dangote-payable-orders'
    | '/dangote-products'
    | '/delivery-customer'
    | '/delivery-inventory'
    | '/delivery-operations'
    | '/deposits'
    | '/depots'
    | '/drivers'
    | '/expense-requests'
    | '/expenses'
    | '/feedback-dashboard'
    | '/filing-stations'
    | '/fleet-ledger'
    | '/fleet-trucks'
    | '/home'
    | '/inventory'
    | '/licence-verification'
    | '/lpg-order-request'
    | '/lpg-orders'
    | '/lpg-payable-orders'
    | '/lpg-stations'
    | '/lpg'
    | '/messaging'
    | '/my-report'
    | '/order-audit'
    | '/order-management'
    | '/orders-pfi'
    | '/orders'
    | '/overpayment-refunds'
    | '/overpayment-requests'
    | '/overview'
    | '/payable-orders'
    | '/payment-verify'
    | '/people'
    | '/pfi'
    | '/product-manager-view'
    | '/product-pricing'
    | '/products'
    | '/profile'
    | '/sales-ledger'
    | '/sales-manager-view'
    | '/security-report'
    | '/ticket'
    | '/vendors'
    | '/lpg/dashboard'
    | '/lpg/plants'
    | '/lpg/sales'
    | '/lpg/stock'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/set-password'
    | '/admin-order/dangote-request-form'
    | '/admin-order/depot'
    | '/admin-order/lpg-request-form'
    | '/admin/details'
    | '/admin/form'
    | '/admin/update'
    | '/bank-accounts/details'
    | '/bank-accounts/form'
    | '/customers/details'
    | '/customers/form'
    | '/dangote-order-request/review'
    | '/dangote-orders/details'
    | '/dangote-products/details'
    | '/dangote-products/form'
    | '/delivery-customer/details'
    | '/delivery-customer/form'
    | '/delivery-operations/allocate-trucks'
    | '/delivery-operations/allocation-details'
    | '/delivery-operations/details'
    | '/deposits/details'
    | '/deposits/manual-deposit'
    | '/depots/details'
    | '/depots/form'
    | '/drivers/details'
    | '/drivers/form'
    | '/filing-stations/details'
    | '/filing-stations/form'
    | '/licence-verification/review'
    | '/lpg-order-request/review'
    | '/lpg-orders/details'
    | '/lpg-stations/details'
    | '/lpg-stations/form'
    | '/orders/details'
    | '/pfi/details'
    | '/pfi/form'
    | '/products/details'
    | '/products/form'
    | '/sales-ledger/assign-customer'
    | '/sales-ledger/details'
    | '/security/entry'
    | '/security/exit'
    | '/ticket/details'
    | '/ticket/generate'
    | '/vendors/details'
    | '/vendors/form'
    | '/activity/'
    | '/admin-order/'
    | '/admin-reports/'
    | '/admin/'
    | '/bank-accounts/'
    | '/bank-statements/'
    | '/commission-rates/'
    | '/commissions/'
    | '/company-dashboard/'
    | '/confirmed-payments/'
    | '/contacts/'
    | '/customer-desk/'
    | '/customers/'
    | '/dangote-order-request/'
    | '/dangote-orders/'
    | '/dangote-payable-orders/'
    | '/dangote-products/'
    | '/delivery-customer/'
    | '/delivery-inventory/'
    | '/delivery-operations/'
    | '/deposits/'
    | '/depots/'
    | '/drivers/'
    | '/expense-requests/'
    | '/expenses/'
    | '/feedback-dashboard/'
    | '/filing-stations/'
    | '/fleet-ledger/'
    | '/fleet-trucks/'
    | '/home/'
    | '/inventory/'
    | '/licence-verification/'
    | '/lpg-order-request/'
    | '/lpg-orders/'
    | '/lpg-payable-orders/'
    | '/lpg-stations/'
    | '/lpg/'
    | '/messaging/'
    | '/my-report/'
    | '/order-audit/'
    | '/order-management/'
    | '/orders-pfi/'
    | '/orders/'
    | '/overpayment-refunds/'
    | '/overpayment-requests/'
    | '/overview/'
    | '/payable-orders/'
    | '/payment-verify/'
    | '/people/'
    | '/pfi/'
    | '/product-manager-view/'
    | '/product-pricing/'
    | '/products/'
    | '/profile/'
    | '/sales-ledger/'
    | '/sales-manager-view/'
    | '/security-report/'
    | '/ticket/'
    | '/vendors/'
    | '/lpg/dashboard/'
    | '/lpg/plants/'
    | '/lpg/sales/'
    | '/lpg/stock/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SetPasswordRoute: typeof SetPasswordRoute
  AdminOrderDangoteRequestFormRoute: typeof AdminOrderDangoteRequestFormRoute
  AdminOrderDepotRoute: typeof AdminOrderDepotRoute
  AdminOrderLpgRequestFormRoute: typeof AdminOrderLpgRequestFormRoute
  AdminDetailsRoute: typeof AdminDetailsRoute
  AdminFormRoute: typeof AdminFormRoute
  AdminUpdateRoute: typeof AdminUpdateRoute
  BankAccountsDetailsRoute: typeof BankAccountsDetailsRoute
  BankAccountsFormRoute: typeof BankAccountsFormRoute
  CustomersDetailsRoute: typeof CustomersDetailsRoute
  CustomersFormRoute: typeof CustomersFormRoute
  DangoteOrderRequestReviewRoute: typeof DangoteOrderRequestReviewRoute
  DangoteOrdersDetailsRoute: typeof DangoteOrdersDetailsRoute
  DangoteProductsDetailsRoute: typeof DangoteProductsDetailsRoute
  DangoteProductsFormRoute: typeof DangoteProductsFormRoute
  DeliveryCustomerDetailsRoute: typeof DeliveryCustomerDetailsRoute
  DeliveryCustomerFormRoute: typeof DeliveryCustomerFormRoute
  DeliveryOperationsAllocateTrucksRoute: typeof DeliveryOperationsAllocateTrucksRoute
  DeliveryOperationsAllocationDetailsRoute: typeof DeliveryOperationsAllocationDetailsRoute
  DeliveryOperationsDetailsRoute: typeof DeliveryOperationsDetailsRoute
  DepositsDetailsRoute: typeof DepositsDetailsRoute
  DepositsManualDepositRoute: typeof DepositsManualDepositRoute
  DepotsDetailsRoute: typeof DepotsDetailsRoute
  DepotsFormRoute: typeof DepotsFormRoute
  DriversDetailsRoute: typeof DriversDetailsRoute
  DriversFormRoute: typeof DriversFormRoute
  FilingStationsDetailsRoute: typeof FilingStationsDetailsRoute
  FilingStationsFormRoute: typeof FilingStationsFormRoute
  LicenceVerificationReviewRoute: typeof LicenceVerificationReviewRoute
  LpgOrderRequestReviewRoute: typeof LpgOrderRequestReviewRoute
  LpgOrdersDetailsRoute: typeof LpgOrdersDetailsRoute
  LpgStationsDetailsRoute: typeof LpgStationsDetailsRoute
  LpgStationsFormRoute: typeof LpgStationsFormRoute
  OrdersDetailsRoute: typeof OrdersDetailsRoute
  PfiDetailsRoute: typeof PfiDetailsRoute
  PfiFormRoute: typeof PfiFormRoute
  ProductsDetailsRoute: typeof ProductsDetailsRoute
  ProductsFormRoute: typeof ProductsFormRoute
  SalesLedgerAssignCustomerRoute: typeof SalesLedgerAssignCustomerRoute
  SalesLedgerDetailsRoute: typeof SalesLedgerDetailsRoute
  SecurityEntryRoute: typeof SecurityEntryRoute
  SecurityExitRoute: typeof SecurityExitRoute
  TicketDetailsRoute: typeof TicketDetailsRoute
  TicketGenerateRoute: typeof TicketGenerateRoute
  VendorsDetailsRoute: typeof VendorsDetailsRoute
  VendorsFormRoute: typeof VendorsFormRoute
  ActivityIndexRoute: typeof ActivityIndexRoute
  AdminOrderIndexRoute: typeof AdminOrderIndexRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BankAccountsIndexRoute: typeof BankAccountsIndexRoute
  BankStatementsIndexRoute: typeof BankStatementsIndexRoute
  CommissionRatesIndexRoute: typeof CommissionRatesIndexRoute
  CommissionsIndexRoute: typeof CommissionsIndexRoute
  CompanyDashboardIndexRoute: typeof CompanyDashboardIndexRoute
  ConfirmedPaymentsIndexRoute: typeof ConfirmedPaymentsIndexRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
  CustomerDeskIndexRoute: typeof CustomerDeskIndexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  DangoteOrderRequestIndexRoute: typeof DangoteOrderRequestIndexRoute
  DangoteOrdersIndexRoute: typeof DangoteOrdersIndexRoute
  DangotePayableOrdersIndexRoute: typeof DangotePayableOrdersIndexRoute
  DangoteProductsIndexRoute: typeof DangoteProductsIndexRoute
  DeliveryCustomerIndexRoute: typeof DeliveryCustomerIndexRoute
  DeliveryInventoryIndexRoute: typeof DeliveryInventoryIndexRoute
  DeliveryOperationsIndexRoute: typeof DeliveryOperationsIndexRoute
  DepositsIndexRoute: typeof DepositsIndexRoute
  DepotsIndexRoute: typeof DepotsIndexRoute
  DriversIndexRoute: typeof DriversIndexRoute
  ExpenseRequestsIndexRoute: typeof ExpenseRequestsIndexRoute
  ExpensesIndexRoute: typeof ExpensesIndexRoute
  FeedbackDashboardIndexRoute: typeof FeedbackDashboardIndexRoute
  FilingStationsIndexRoute: typeof FilingStationsIndexRoute
  FleetLedgerIndexRoute: typeof FleetLedgerIndexRoute
  FleetTrucksIndexRoute: typeof FleetTrucksIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  LicenceVerificationIndexRoute: typeof LicenceVerificationIndexRoute
  LpgOrderRequestIndexRoute: typeof LpgOrderRequestIndexRoute
  LpgOrdersIndexRoute: typeof LpgOrdersIndexRoute
  LpgPayableOrdersIndexRoute: typeof LpgPayableOrdersIndexRoute
  LpgStationsIndexRoute: typeof LpgStationsIndexRoute
  LpgIndexRoute: typeof LpgIndexRoute
  MessagingIndexRoute: typeof MessagingIndexRoute
  MyReportIndexRoute: typeof MyReportIndexRoute
  OrderAuditIndexRoute: typeof OrderAuditIndexRoute
  OrderManagementIndexRoute: typeof OrderManagementIndexRoute
  OrdersPfiIndexRoute: typeof OrdersPfiIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  OverpaymentRefundsIndexRoute: typeof OverpaymentRefundsIndexRoute
  OverpaymentRequestsIndexRoute: typeof OverpaymentRequestsIndexRoute
  OverviewIndexRoute: typeof OverviewIndexRoute
  PayableOrdersIndexRoute: typeof PayableOrdersIndexRoute
  PaymentVerifyIndexRoute: typeof PaymentVerifyIndexRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
  PfiIndexRoute: typeof PfiIndexRoute
  ProductManagerViewIndexRoute: typeof ProductManagerViewIndexRoute
  ProductPricingIndexRoute: typeof ProductPricingIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  SalesLedgerIndexRoute: typeof SalesLedgerIndexRoute
  SalesManagerViewIndexRoute: typeof SalesManagerViewIndexRoute
  SecurityReportIndexRoute: typeof SecurityReportIndexRoute
  TicketIndexRoute: typeof TicketIndexRoute
  VendorsIndexRoute: typeof VendorsIndexRoute
  LpgDashboardIndexRoute: typeof LpgDashboardIndexRoute
  LpgPlantsIndexRoute: typeof LpgPlantsIndexRoute
  LpgSalesIndexRoute: typeof LpgSalesIndexRoute
  LpgStockIndexRoute: typeof LpgStockIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/': {
      id: '/activity/'
      path: '/activity'
      fullPath: '/activity/'
      preLoaderRoute: typeof ActivityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-order/': {
      id: '/admin-order/'
      path: '/admin-order'
      fullPath: '/admin-order/'
      preLoaderRoute: typeof AdminOrderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-order/dangote-request-form': {
      id: '/admin-order/dangote-request-form'
      path: '/admin-order/dangote-request-form'
      fullPath: '/admin-order/dangote-request-form'
      preLoaderRoute: typeof AdminOrderDangoteRequestFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-order/depot': {
      id: '/admin-order/depot'
      path: '/admin-order/depot'
      fullPath: '/admin-order/depot'
      preLoaderRoute: typeof AdminOrderDepotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-order/lpg-request-form': {
      id: '/admin-order/lpg-request-form'
      path: '/admin-order/lpg-request-form'
      fullPath: '/admin-order/lpg-request-form'
      preLoaderRoute: typeof AdminOrderLpgRequestFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-reports/': {
      id: '/admin-reports/'
      path: '/admin-reports'
      fullPath: '/admin-reports/'
      preLoaderRoute: typeof AdminReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/details': {
      id: '/admin/details'
      path: '/admin/details'
      fullPath: '/admin/details'
      preLoaderRoute: typeof AdminDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/form': {
      id: '/admin/form'
      path: '/admin/form'
      fullPath: '/admin/form'
      preLoaderRoute: typeof AdminFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/update': {
      id: '/admin/update'
      path: '/admin/update'
      fullPath: '/admin/update'
      preLoaderRoute: typeof AdminUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-accounts/': {
      id: '/bank-accounts/'
      path: '/bank-accounts'
      fullPath: '/bank-accounts/'
      preLoaderRoute: typeof BankAccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-accounts/details': {
      id: '/bank-accounts/details'
      path: '/bank-accounts/details'
      fullPath: '/bank-accounts/details'
      preLoaderRoute: typeof BankAccountsDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-accounts/form': {
      id: '/bank-accounts/form'
      path: '/bank-accounts/form'
      fullPath: '/bank-accounts/form'
      preLoaderRoute: typeof BankAccountsFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-statements/': {
      id: '/bank-statements/'
      path: '/bank-statements'
      fullPath: '/bank-statements/'
      preLoaderRoute: typeof BankStatementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commission-rates/': {
      id: '/commission-rates/'
      path: '/commission-rates'
      fullPath: '/commission-rates/'
      preLoaderRoute: typeof CommissionRatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commissions/': {
      id: '/commissions/'
      path: '/commissions'
      fullPath: '/commissions/'
      preLoaderRoute: typeof CommissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-dashboard/': {
      id: '/company-dashboard/'
      path: '/company-dashboard'
      fullPath: '/company-dashboard/'
      preLoaderRoute: typeof CompanyDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmed-payments/': {
      id: '/confirmed-payments/'
      path: '/confirmed-payments'
      fullPath: '/confirmed-payments/'
      preLoaderRoute: typeof ConfirmedPaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-desk/': {
      id: '/customer-desk/'
      path: '/customer-desk'
      fullPath: '/customer-desk/'
      preLoaderRoute: typeof CustomerDeskIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/details': {
      id: '/customers/details'
      path: '/customers/details'
      fullPath: '/customers/details'
      preLoaderRoute: typeof CustomersDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/form': {
      id: '/customers/form'
      path: '/customers/form'
      fullPath: '/customers/form'
      preLoaderRoute: typeof CustomersFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dangote-order-request/': {
      id: '/dangote-order-request/'
      path: '/dangote-order-request'
      fullPath: '/dangote-order-request/'
      preLoaderRoute: typeof DangoteOrderRequestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dangote-order-request/review': {
      id: '/dangote-order-request/review'
      path: '/dangote-order-request/review'
      fullPath: '/dangote-order-request/review'
      preLoaderRoute: typeof DangoteOrderRequestReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dangote-orders/': {
      id: '/dangote-orders/'
      path: '/dangote-orders'
      fullPath: '/dangote-orders/'
      preLoaderRoute: typeof DangoteOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dangote-orders/details': {
      id: '/dangote-orders/details'
      path: '/dangote-orders/details'
      fullPath: '/dangote-orders/details'
      preLoaderRoute: typeof DangoteOrdersDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dangote-payable-orders/': {
      id: '/dangote-payable-orders/'
      path: '/dangote-payable-orders'
      fullPath: '/dangote-payable-orders/'
      preLoaderRoute: typeof DangotePayableOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dangote-products/': {
      id: '/dangote-products/'
      path: '/dangote-products'
      fullPath: '/dangote-products/'
      preLoaderRoute: typeof DangoteProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dangote-products/details': {
      id: '/dangote-products/details'
      path: '/dangote-products/details'
      fullPath: '/dangote-products/details'
      preLoaderRoute: typeof DangoteProductsDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dangote-products/form': {
      id: '/dangote-products/form'
      path: '/dangote-products/form'
      fullPath: '/dangote-products/form'
      preLoaderRoute: typeof DangoteProductsFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-customer/': {
      id: '/delivery-customer/'
      path: '/delivery-customer'
      fullPath: '/delivery-customer/'
      preLoaderRoute: typeof DeliveryCustomerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-customer/details': {
      id: '/delivery-customer/details'
      path: '/delivery-customer/details'
      fullPath: '/delivery-customer/details'
      preLoaderRoute: typeof DeliveryCustomerDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-customer/form': {
      id: '/delivery-customer/form'
      path: '/delivery-customer/form'
      fullPath: '/delivery-customer/form'
      preLoaderRoute: typeof DeliveryCustomerFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-inventory/': {
      id: '/delivery-inventory/'
      path: '/delivery-inventory'
      fullPath: '/delivery-inventory/'
      preLoaderRoute: typeof DeliveryInventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-operations/': {
      id: '/delivery-operations/'
      path: '/delivery-operations'
      fullPath: '/delivery-operations/'
      preLoaderRoute: typeof DeliveryOperationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-operations/allocate-trucks': {
      id: '/delivery-operations/allocate-trucks'
      path: '/delivery-operations/allocate-trucks'
      fullPath: '/delivery-operations/allocate-trucks'
      preLoaderRoute: typeof DeliveryOperationsAllocateTrucksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-operations/allocation-details': {
      id: '/delivery-operations/allocation-details'
      path: '/delivery-operations/allocation-details'
      fullPath: '/delivery-operations/allocation-details'
      preLoaderRoute: typeof DeliveryOperationsAllocationDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-operations/details': {
      id: '/delivery-operations/details'
      path: '/delivery-operations/details'
      fullPath: '/delivery-operations/details'
      preLoaderRoute: typeof DeliveryOperationsDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposits/': {
      id: '/deposits/'
      path: '/deposits'
      fullPath: '/deposits/'
      preLoaderRoute: typeof DepositsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposits/details': {
      id: '/deposits/details'
      path: '/deposits/details'
      fullPath: '/deposits/details'
      preLoaderRoute: typeof DepositsDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposits/manual-deposit': {
      id: '/deposits/manual-deposit'
      path: '/deposits/manual-deposit'
      fullPath: '/deposits/manual-deposit'
      preLoaderRoute: typeof DepositsManualDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depots/': {
      id: '/depots/'
      path: '/depots'
      fullPath: '/depots/'
      preLoaderRoute: typeof DepotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depots/details': {
      id: '/depots/details'
      path: '/depots/details'
      fullPath: '/depots/details'
      preLoaderRoute: typeof DepotsDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depots/form': {
      id: '/depots/form'
      path: '/depots/form'
      fullPath: '/depots/form'
      preLoaderRoute: typeof DepotsFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers/': {
      id: '/drivers/'
      path: '/drivers'
      fullPath: '/drivers/'
      preLoaderRoute: typeof DriversIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers/details': {
      id: '/drivers/details'
      path: '/drivers/details'
      fullPath: '/drivers/details'
      preLoaderRoute: typeof DriversDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers/form': {
      id: '/drivers/form'
      path: '/drivers/form'
      fullPath: '/drivers/form'
      preLoaderRoute: typeof DriversFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expense-requests/': {
      id: '/expense-requests/'
      path: '/expense-requests'
      fullPath: '/expense-requests/'
      preLoaderRoute: typeof ExpenseRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/': {
      id: '/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof ExpensesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback-dashboard/': {
      id: '/feedback-dashboard/'
      path: '/feedback-dashboard'
      fullPath: '/feedback-dashboard/'
      preLoaderRoute: typeof FeedbackDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filing-stations/': {
      id: '/filing-stations/'
      path: '/filing-stations'
      fullPath: '/filing-stations/'
      preLoaderRoute: typeof FilingStationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filing-stations/details': {
      id: '/filing-stations/details'
      path: '/filing-stations/details'
      fullPath: '/filing-stations/details'
      preLoaderRoute: typeof FilingStationsDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filing-stations/form': {
      id: '/filing-stations/form'
      path: '/filing-stations/form'
      fullPath: '/filing-stations/form'
      preLoaderRoute: typeof FilingStationsFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet-ledger/': {
      id: '/fleet-ledger/'
      path: '/fleet-ledger'
      fullPath: '/fleet-ledger/'
      preLoaderRoute: typeof FleetLedgerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet-trucks/': {
      id: '/fleet-trucks/'
      path: '/fleet-trucks'
      fullPath: '/fleet-trucks/'
      preLoaderRoute: typeof FleetTrucksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licence-verification/': {
      id: '/licence-verification/'
      path: '/licence-verification'
      fullPath: '/licence-verification/'
      preLoaderRoute: typeof LicenceVerificationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licence-verification/review': {
      id: '/licence-verification/review'
      path: '/licence-verification/review'
      fullPath: '/licence-verification/review'
      preLoaderRoute: typeof LicenceVerificationReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lpg-order-request/': {
      id: '/lpg-order-request/'
      path: '/lpg-order-request'
      fullPath: '/lpg-order-request/'
      preLoaderRoute: typeof LpgOrderRequestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lpg-order-request/review': {
      id: '/lpg-order-request/review'
      path: '/lpg-order-request/review'
      fullPath: '/lpg-order-request/review'
      preLoaderRoute: typeof LpgOrderRequestReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lpg-orders/': {
      id: '/lpg-orders/'
      path: '/lpg-orders'
      fullPath: '/lpg-orders/'
      preLoaderRoute: typeof LpgOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lpg-orders/details': {
      id: '/lpg-orders/details'
      path: '/lpg-orders/details'
      fullPath: '/lpg-orders/details'
      preLoaderRoute: typeof LpgOrdersDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lpg-payable-orders/': {
      id: '/lpg-payable-orders/'
      path: '/lpg-payable-orders'
      fullPath: '/lpg-payable-orders/'
      preLoaderRoute: typeof LpgPayableOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lpg-stations/': {
      id: '/lpg-stations/'
      path: '/lpg-stations'
      fullPath: '/lpg-stations/'
      preLoaderRoute: typeof LpgStationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lpg-stations/details': {
      id: '/lpg-stations/details'
      path: '/lpg-stations/details'
      fullPath: '/lpg-stations/details'
      preLoaderRoute: typeof LpgStationsDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lpg-stations/form': {
      id: '/lpg-stations/form'
      path: '/lpg-stations/form'
      fullPath: '/lpg-stations/form'
      preLoaderRoute: typeof LpgStationsFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lpg/': {
      id: '/lpg/'
      path: '/lpg'
      fullPath: '/lpg/'
      preLoaderRoute: typeof LpgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messaging/': {
      id: '/messaging/'
      path: '/messaging'
      fullPath: '/messaging/'
      preLoaderRoute: typeof MessagingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-report/': {
      id: '/my-report/'
      path: '/my-report'
      fullPath: '/my-report/'
      preLoaderRoute: typeof MyReportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-audit/': {
      id: '/order-audit/'
      path: '/order-audit'
      fullPath: '/order-audit/'
      preLoaderRoute: typeof OrderAuditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-management/': {
      id: '/order-management/'
      path: '/order-management'
      fullPath: '/order-management/'
      preLoaderRoute: typeof OrderManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders-pfi/': {
      id: '/orders-pfi/'
      path: '/orders-pfi'
      fullPath: '/orders-pfi/'
      preLoaderRoute: typeof OrdersPfiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/details': {
      id: '/orders/details'
      path: '/orders/details'
      fullPath: '/orders/details'
      preLoaderRoute: typeof OrdersDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overpayment-refunds/': {
      id: '/overpayment-refunds/'
      path: '/overpayment-refunds'
      fullPath: '/overpayment-refunds/'
      preLoaderRoute: typeof OverpaymentRefundsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overpayment-requests/': {
      id: '/overpayment-requests/'
      path: '/overpayment-requests'
      fullPath: '/overpayment-requests/'
      preLoaderRoute: typeof OverpaymentRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview/': {
      id: '/overview/'
      path: '/overview'
      fullPath: '/overview/'
      preLoaderRoute: typeof OverviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payable-orders/': {
      id: '/payable-orders/'
      path: '/payable-orders'
      fullPath: '/payable-orders/'
      preLoaderRoute: typeof PayableOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-verify/': {
      id: '/payment-verify/'
      path: '/payment-verify'
      fullPath: '/payment-verify/'
      preLoaderRoute: typeof PaymentVerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/': {
      id: '/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pfi/': {
      id: '/pfi/'
      path: '/pfi'
      fullPath: '/pfi/'
      preLoaderRoute: typeof PfiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pfi/details': {
      id: '/pfi/details'
      path: '/pfi/details'
      fullPath: '/pfi/details'
      preLoaderRoute: typeof PfiDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pfi/form': {
      id: '/pfi/form'
      path: '/pfi/form'
      fullPath: '/pfi/form'
      preLoaderRoute: typeof PfiFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-manager-view/': {
      id: '/product-manager-view/'
      path: '/product-manager-view'
      fullPath: '/product-manager-view/'
      preLoaderRoute: typeof ProductManagerViewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-pricing/': {
      id: '/product-pricing/'
      path: '/product-pricing'
      fullPath: '/product-pricing/'
      preLoaderRoute: typeof ProductPricingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/details': {
      id: '/products/details'
      path: '/products/details'
      fullPath: '/products/details'
      preLoaderRoute: typeof ProductsDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/form': {
      id: '/products/form'
      path: '/products/form'
      fullPath: '/products/form'
      preLoaderRoute: typeof ProductsFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-ledger/': {
      id: '/sales-ledger/'
      path: '/sales-ledger'
      fullPath: '/sales-ledger/'
      preLoaderRoute: typeof SalesLedgerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-ledger/assign-customer': {
      id: '/sales-ledger/assign-customer'
      path: '/sales-ledger/assign-customer'
      fullPath: '/sales-ledger/assign-customer'
      preLoaderRoute: typeof SalesLedgerAssignCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-ledger/details': {
      id: '/sales-ledger/details'
      path: '/sales-ledger/details'
      fullPath: '/sales-ledger/details'
      preLoaderRoute: typeof SalesLedgerDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-manager-view/': {
      id: '/sales-manager-view/'
      path: '/sales-manager-view'
      fullPath: '/sales-manager-view/'
      preLoaderRoute: typeof SalesManagerViewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-report/': {
      id: '/security-report/'
      path: '/security-report'
      fullPath: '/security-report/'
      preLoaderRoute: typeof SecurityReportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/entry': {
      id: '/security/entry'
      path: '/security/entry'
      fullPath: '/security/entry'
      preLoaderRoute: typeof SecurityEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/exit': {
      id: '/security/exit'
      path: '/security/exit'
      fullPath: '/security/exit'
      preLoaderRoute: typeof SecurityExitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/': {
      id: '/ticket/'
      path: '/ticket'
      fullPath: '/ticket/'
      preLoaderRoute: typeof TicketIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/details': {
      id: '/ticket/details'
      path: '/ticket/details'
      fullPath: '/ticket/details'
      preLoaderRoute: typeof TicketDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/generate': {
      id: '/ticket/generate'
      path: '/ticket/generate'
      fullPath: '/ticket/generate'
      preLoaderRoute: typeof TicketGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/': {
      id: '/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof VendorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/details': {
      id: '/vendors/details'
      path: '/vendors/details'
      fullPath: '/vendors/details'
      preLoaderRoute: typeof VendorsDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/form': {
      id: '/vendors/form'
      path: '/vendors/form'
      fullPath: '/vendors/form'
      preLoaderRoute: typeof VendorsFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lpg/dashboard/': {
      id: '/lpg/dashboard/'
      path: '/lpg/dashboard'
      fullPath: '/lpg/dashboard/'
      preLoaderRoute: typeof LpgDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lpg/plants/': {
      id: '/lpg/plants/'
      path: '/lpg/plants'
      fullPath: '/lpg/plants/'
      preLoaderRoute: typeof LpgPlantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lpg/sales/': {
      id: '/lpg/sales/'
      path: '/lpg/sales'
      fullPath: '/lpg/sales/'
      preLoaderRoute: typeof LpgSalesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lpg/stock/': {
      id: '/lpg/stock/'
      path: '/lpg/stock'
      fullPath: '/lpg/stock/'
      preLoaderRoute: typeof LpgStockIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SetPasswordRoute: SetPasswordRoute,
  AdminOrderDangoteRequestFormRoute: AdminOrderDangoteRequestFormRoute,
  AdminOrderDepotRoute: AdminOrderDepotRoute,
  AdminOrderLpgRequestFormRoute: AdminOrderLpgRequestFormRoute,
  AdminDetailsRoute: AdminDetailsRoute,
  AdminFormRoute: AdminFormRoute,
  AdminUpdateRoute: AdminUpdateRoute,
  BankAccountsDetailsRoute: BankAccountsDetailsRoute,
  BankAccountsFormRoute: BankAccountsFormRoute,
  CustomersDetailsRoute: CustomersDetailsRoute,
  CustomersFormRoute: CustomersFormRoute,
  DangoteOrderRequestReviewRoute: DangoteOrderRequestReviewRoute,
  DangoteOrdersDetailsRoute: DangoteOrdersDetailsRoute,
  DangoteProductsDetailsRoute: DangoteProductsDetailsRoute,
  DangoteProductsFormRoute: DangoteProductsFormRoute,
  DeliveryCustomerDetailsRoute: DeliveryCustomerDetailsRoute,
  DeliveryCustomerFormRoute: DeliveryCustomerFormRoute,
  DeliveryOperationsAllocateTrucksRoute: DeliveryOperationsAllocateTrucksRoute,
  DeliveryOperationsAllocationDetailsRoute:
    DeliveryOperationsAllocationDetailsRoute,
  DeliveryOperationsDetailsRoute: DeliveryOperationsDetailsRoute,
  DepositsDetailsRoute: DepositsDetailsRoute,
  DepositsManualDepositRoute: DepositsManualDepositRoute,
  DepotsDetailsRoute: DepotsDetailsRoute,
  DepotsFormRoute: DepotsFormRoute,
  DriversDetailsRoute: DriversDetailsRoute,
  DriversFormRoute: DriversFormRoute,
  FilingStationsDetailsRoute: FilingStationsDetailsRoute,
  FilingStationsFormRoute: FilingStationsFormRoute,
  LicenceVerificationReviewRoute: LicenceVerificationReviewRoute,
  LpgOrderRequestReviewRoute: LpgOrderRequestReviewRoute,
  LpgOrdersDetailsRoute: LpgOrdersDetailsRoute,
  LpgStationsDetailsRoute: LpgStationsDetailsRoute,
  LpgStationsFormRoute: LpgStationsFormRoute,
  OrdersDetailsRoute: OrdersDetailsRoute,
  PfiDetailsRoute: PfiDetailsRoute,
  PfiFormRoute: PfiFormRoute,
  ProductsDetailsRoute: ProductsDetailsRoute,
  ProductsFormRoute: ProductsFormRoute,
  SalesLedgerAssignCustomerRoute: SalesLedgerAssignCustomerRoute,
  SalesLedgerDetailsRoute: SalesLedgerDetailsRoute,
  SecurityEntryRoute: SecurityEntryRoute,
  SecurityExitRoute: SecurityExitRoute,
  TicketDetailsRoute: TicketDetailsRoute,
  TicketGenerateRoute: TicketGenerateRoute,
  VendorsDetailsRoute: VendorsDetailsRoute,
  VendorsFormRoute: VendorsFormRoute,
  ActivityIndexRoute: ActivityIndexRoute,
  AdminOrderIndexRoute: AdminOrderIndexRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  BankAccountsIndexRoute: BankAccountsIndexRoute,
  BankStatementsIndexRoute: BankStatementsIndexRoute,
  CommissionRatesIndexRoute: CommissionRatesIndexRoute,
  CommissionsIndexRoute: CommissionsIndexRoute,
  CompanyDashboardIndexRoute: CompanyDashboardIndexRoute,
  ConfirmedPaymentsIndexRoute: ConfirmedPaymentsIndexRoute,
  ContactsIndexRoute: ContactsIndexRoute,
  CustomerDeskIndexRoute: CustomerDeskIndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  DangoteOrderRequestIndexRoute: DangoteOrderRequestIndexRoute,
  DangoteOrdersIndexRoute: DangoteOrdersIndexRoute,
  DangotePayableOrdersIndexRoute: DangotePayableOrdersIndexRoute,
  DangoteProductsIndexRoute: DangoteProductsIndexRoute,
  DeliveryCustomerIndexRoute: DeliveryCustomerIndexRoute,
  DeliveryInventoryIndexRoute: DeliveryInventoryIndexRoute,
  DeliveryOperationsIndexRoute: DeliveryOperationsIndexRoute,
  DepositsIndexRoute: DepositsIndexRoute,
  DepotsIndexRoute: DepotsIndexRoute,
  DriversIndexRoute: DriversIndexRoute,
  ExpenseRequestsIndexRoute: ExpenseRequestsIndexRoute,
  ExpensesIndexRoute: ExpensesIndexRoute,
  FeedbackDashboardIndexRoute: FeedbackDashboardIndexRoute,
  FilingStationsIndexRoute: FilingStationsIndexRoute,
  FleetLedgerIndexRoute: FleetLedgerIndexRoute,
  FleetTrucksIndexRoute: FleetTrucksIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  LicenceVerificationIndexRoute: LicenceVerificationIndexRoute,
  LpgOrderRequestIndexRoute: LpgOrderRequestIndexRoute,
  LpgOrdersIndexRoute: LpgOrdersIndexRoute,
  LpgPayableOrdersIndexRoute: LpgPayableOrdersIndexRoute,
  LpgStationsIndexRoute: LpgStationsIndexRoute,
  LpgIndexRoute: LpgIndexRoute,
  MessagingIndexRoute: MessagingIndexRoute,
  MyReportIndexRoute: MyReportIndexRoute,
  OrderAuditIndexRoute: OrderAuditIndexRoute,
  OrderManagementIndexRoute: OrderManagementIndexRoute,
  OrdersPfiIndexRoute: OrdersPfiIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  OverpaymentRefundsIndexRoute: OverpaymentRefundsIndexRoute,
  OverpaymentRequestsIndexRoute: OverpaymentRequestsIndexRoute,
  OverviewIndexRoute: OverviewIndexRoute,
  PayableOrdersIndexRoute: PayableOrdersIndexRoute,
  PaymentVerifyIndexRoute: PaymentVerifyIndexRoute,
  PeopleIndexRoute: PeopleIndexRoute,
  PfiIndexRoute: PfiIndexRoute,
  ProductManagerViewIndexRoute: ProductManagerViewIndexRoute,
  ProductPricingIndexRoute: ProductPricingIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  SalesLedgerIndexRoute: SalesLedgerIndexRoute,
  SalesManagerViewIndexRoute: SalesManagerViewIndexRoute,
  SecurityReportIndexRoute: SecurityReportIndexRoute,
  TicketIndexRoute: TicketIndexRoute,
  VendorsIndexRoute: VendorsIndexRoute,
  LpgDashboardIndexRoute: LpgDashboardIndexRoute,
  LpgPlantsIndexRoute: LpgPlantsIndexRoute,
  LpgSalesIndexRoute: LpgSalesIndexRoute,
  LpgStockIndexRoute: LpgStockIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
